#!/usr/bin/env bash

if [ -n "${JAVA_HOME}" ]; then
  RUNNER="${JAVA_HOME}/bin/java"
else
  if [ `command -v java` ]; then
    RUNNER="java"
  else
    echo "JAVA_HOME is not set" >&2
    exit 1
  fi
fi


echo "runner=$RUNNER"
ROOT_DIR="/tmp/sc"
JAR_DIR="/home/hdpusr/workspace/sclib-spark/target"
MASTER="local[2]"
SQL="select name,prov,age from person"
INPUTTABLES="person||String name;int age;String prov||/home/hdpusr/workspace/sclib-spark/person"
OUTPUTTABLE="age||String name;String prov;int age||/tmp/ds"

echo "$RUNNER" -cp "${ROOT_DIR}/spark/*:${JAR_DIR}/sclib-spark-0.0.1-SNAPSHOT.jar"  com.kzx.dw.DataSetApp ${ROOT_DIR} ${MASTER}  \"${SQL}\"  \"${INPUTTABLES}\" \"${OUTPUTTABLE}\"

exec "$RUNNER" -cp "${ROOT_DIR}/spark/*:${JAR_DIR}/sclib-spark-0.0.1-SNAPSHOT.jar"  com.kzx.dw.DataSetApp ${ROOT_DIR} ${MASTER}  \"${SQL}\"  \"${INPUTTABLES}\" \"${OUTPUTTABLE}\"
